# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ ]
  pull_request:
    branches: [  ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      VERSION: 1.6.2
      ARCHITECTURE: x64
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo apt install xz-utils
          wget https://nim-lang.org/download/nim-$VERSION-linux_$ARCHITECTURE.tar.xz
          mkdir nim
          tar -xf nim-$VERSION-linux_$ARCHITECTURE.tar.xz -C ./nim
          rm nim-$VERSION-linux_$ARCHITECTURE.tar.xz
          
      - name: zip files
        run: |
          cd nim
          zip -r ./nim-linux-$VERSION_$ARCHITECTURE.zip .
          mv nim-linux-$VERSION_$ARCHITECTURE.zip ..
          cd ..

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: Updated version of nim
          tag_name: 1.6.2
          files: nim-linux-1.6.2_x64.zip
  
