# This is a basic workflow to help you get started with Actions

name: CI-ubuntu

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      VERSION: 1.6.2
      ARCHITECTURE: x64
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo apt install xz-utils
          wget https://nim-lang.org/download/nim-$VERSION-linux_$ARCHITECTURE.tar.xz
          mkdir nim
          tar -xf nim-$VERSION-linux_$ARCHITECTURE.tar.xz -C ./nim
          rm nim-$VERSION-linux_$ARCHITECTURE.tar.xz
          
      - name: zip files
        run: |
          cd nim
          ls
          zip -r ./nim-linux-$VERSION_$ARCHITECTURE.zip .
          ls
          mv nim-linux-$VERSION_$ARCHITECTURE.zip ..
          ls
          cd ..

      - uses: actions/upload-artifact@v2
        with:
          name: nim-1.6.2
          path: ./nim-linux-1.6.2_x64.zip
