# This is a basic workflow to help you get started with Actions

name: CI-Windows

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Download File To Workspace
        uses: carlosperate/download-file-action@v1.1.0
        with:
          file-url: https://nim-lang.org/download/nim-1.6.2_x64.zip
      
      - name: Build Binary
        shell: cmd
        run: move nim-1.6.2_x64.zip nim-windows-1.6.2_x64.zip
  
      - name: Download artifact
      # You may pin to the exact commit or the version.
      # uses: aochmann/actions-download-artifact@5709392f11b5937bd316e52687ad87f7deced5f5
        uses: aochmann/actions-download-artifact@1.0.4
        with:
          # Artifact name (download all artifacts in not specified)
          name: nim-linux-1.6.2_x64.zip
    
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: Updated version of nim
          tag_name: 1.6.2
          files: |
            nim-windows-1.6.2_x64.zip
            nim-linux-1.6.2_x64.zip
